language: node_js
sudo: false
node_js:
  - "8.1.3"
install:
  - npm install
script:
  - npm test
env:
  - DV_HOST=127.0.0.1
  - DB_USER=root
  - DB_PASSWORD=
  - DB_DATABASE=koa_vue_notes_testing
  before_script:
  - mysql -u root -e 'CREATE DATABASE koa_vue_notes_testing;'